### ISSUE TITLE
Web3Go 官网 Recommended reading 同步链接medium最新文章

### ISSUE THREAD

**Issue by natelindev** [web3go-xyz/web3go-official-website#6]
![Image](https://github.com/web3go-xyz/web3go-official-website/assets/135939455/eeb16945-b8fb-4760-9140-4998df17a6c4)

**Comment by natelindev** [comment]
need to fix API: https://app.web3go.xyz/backconfig-api/website/webNews/list?pageNum=1&pageSize=10 return values

**Comment by natelindev** [comment]
not sure where the source code are

**Comment by happyJ2024** [comment]
[@Jennie Liu](https://web3go.slack.com/team/U05BKJVJSGY)
 
[@stan](https://web3go.slack.com/team/U05J17Q8LMB)
 Web3Go 官网 Recommended reading 同步链接medium最新文章
--- 这个去维护
--http://13.251.111.178:8081/#/login?redirect=%2Findex
 web3go-official-backend-
account:  admin
password:   web3go123
